# Generated by Django 4.2.10 on 2025-06-25 13:53

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth', null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], max_length=20, null=True)),
                ('preferred_language', models.CharField(choices=[('EN', 'English'), ('HI', 'Hindi'), ('TA', 'Tamil'), ('TE', 'Telugu'), ('BN', 'Bengali'), ('MR', 'Marathi'), ('GU', 'Gujarati'), ('KN', 'Kannada'), ('ML', 'Malayalam'), ('PA', 'Punjabi')], default='EN', max_length=10)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('address', models.TextField(blank=True, help_text='Legacy address field - use addresses relation instead', null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verification_token', models.CharField(blank=True, max_length=128, null=True)),
                ('reset_password_token', models.CharField(blank=True, max_length=128, null=True)),
                ('reset_password_expires', models.DateTimeField(blank=True, null=True)),
                ('failed_login_attempts', models.PositiveIntegerField(default=0)),
                ('last_failed_login', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(blank=True, help_text='Session identifier for guest users', max_length=100, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Cart expiration time', null=True)),
                ('applied_coupon', models.CharField(blank=True, max_length=50, null=True)),
                ('coupon_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Unique order number', max_length=50, unique=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PLACED', 'Placed'), ('CONFIRMED', 'Confirmed'), ('PAID', 'Paid'), ('PROCESSING', 'Processing'), ('PACKED', 'Packed'), ('SHIPPED', 'Shipped'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PLACED', max_length=25)),
                ('legacy_shipping_address', models.TextField(blank=True, help_text='Legacy shipping address field - use shipping_address relation instead', null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('carrier_name', models.CharField(blank=True, max_length=100, null=True)),
                ('estimated_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_instructions', models.TextField(blank=True, help_text='Special delivery instructions', null=True)),
                ('preferred_delivery_time', models.CharField(choices=[('MORNING', '9 AM - 12 PM'), ('AFTERNOON', '12 PM - 6 PM'), ('EVENING', '6 PM - 9 PM'), ('ANYTIME', 'Anytime')], default='ANYTIME', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal before taxes and shipping', max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total tax amount', max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, help_text='Shipping cost', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total discount amount', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Final total amount', max_digits=12)),
                ('coupon_code', models.CharField(blank=True, max_length=50, null=True)),
                ('coupon_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Internal order notes', null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending'), ('EXPIRED', 'Expired')], max_length=20)),
                ('payment_type', models.CharField(choices=[('CARD', 'Card Payment'), ('UPI', 'UPI Payment'), ('WALLET', 'Wallet Payment'), ('NET_BANKING', 'Net Banking'), ('COD', 'Cash on Delivery'), ('EMI', 'EMI Payment'), ('GIFT_CARD', 'Gift Card'), ('STORE_CREDIT', 'Store Credit')], max_length=25)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('payment_gateway_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method_id', models.CharField(max_length=100, null=True)),
                ('gateway_name', models.CharField(blank=True, help_text='Payment gateway used', max_length=50, null=True)),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('gateway_response', models.JSONField(blank=True, help_text='Full gateway response', null=True)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Tax amount', max_digits=10)),
                ('convenience_fee', models.DecimalField(decimal_places=2, default=0, help_text='Convenience fee', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Discount amount', max_digits=10)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total refunded amount', max_digits=10)),
                ('refund_reason', models.TextField(blank=True, help_text='Reason for refund', null=True)),
                ('refund_processed_at', models.DateTimeField(blank=True, null=True)),
                ('legacy_billing_address', models.TextField(blank=True, help_text='Legacy billing address field - use billing_address relation instead', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, help_text='Reason for payment failure', null=True)),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of retry attempts')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Payment expiration time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(help_text='Name of the person at this address', max_length=255)),
                ('street_address', models.CharField(help_text='Street address line 1', max_length=500)),
                ('street_address_2', models.CharField(blank=True, help_text='Street address line 2 (optional)', max_length=255, null=True)),
                ('landmark', models.CharField(blank=True, help_text='Nearby landmark for easy identification', max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin_code', models.CharField(help_text='Postal/ZIP code', max_length=10, validators=[django.core.validators.RegexValidator(message='PIN code must be 6 digits for Indian addresses.', regex='^\\d{6}$')])),
                ('country', models.CharField(default='India', max_length=100)),
                ('phone_number', models.CharField(help_text='Contact phone number', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address_type', models.CharField(choices=[('HOME', 'Home'), ('WORK', 'Work'), ('OFFICE', 'Office'), ('OTHER', 'Other')], default='HOME', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='Latitude coordinate', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='Longitude coordinate', max_digits=11, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this address has been verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UPIPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upi_id', models.CharField(max_length=255)),
                ('upi_nickname', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upi_payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_history_group', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('results_count', models.IntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('search_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='authentication.searchhistorygroup')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gateway_response', models.JSONField(null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='authentication.paymenthistory')),
            ],
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='billing_address',
            field=models.ForeignKey(blank=True, help_text='Detailed billing address', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_payments', to='authentication.useraddress'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='authentication.order'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(help_text='Product identifier', max_length=100)),
                ('product_name', models.CharField(help_text='Product name at time of order', max_length=255)),
                ('product_description', models.TextField(blank=True, help_text='Product description', null=True)),
                ('product_image_url', models.URLField(blank=True, null=True)),
                ('product_sku', models.CharField(blank=True, help_text='Product SKU', max_length=100, null=True)),
                ('product_variant', models.JSONField(blank=True, help_text='Product variants (size, color, weight, etc.)', null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PACKED', 'Packed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, help_text='Item weight in kg', max_digits=8, null=True)),
                ('dimensions', models.JSONField(blank=True, help_text='Item dimensions (length, width, height)', null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='authentication.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, help_text='Detailed shipping address', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipping_orders', to='authentication.useraddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ExpiringToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('device_type', models.CharField(choices=[('ANDROID', 'Android App'), ('WEB', 'Web Browser'), ('IOS', 'iOS App'), ('API', 'API Client')], default='API', max_length=20)),
                ('device_id', models.CharField(blank=True, help_text='Unique device identifier', max_length=255, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address when token was created', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_user_message', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attachment_url', models.URLField(blank=True, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='authentication.customersupportticket')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(help_text='Product identifier', max_length=100)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_image_url', models.URLField(blank=True, null=True)),
                ('product_sku', models.CharField(blank=True, max_length=100, null=True)),
                ('product_variant', models.JSONField(blank=True, help_text='Product variants (size, color, weight, etc.)', null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_available', models.BooleanField(default=True, help_text='Whether product is currently available')),
                ('stock_quantity', models.PositiveIntegerField(blank=True, help_text='Available stock quantity', null=True)),
                ('is_saved_for_later', models.BooleanField(default=False, help_text='Saved for later (wishlist)')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='authentication.cart')),
            ],
        ),
        migrations.CreateModel(
            name='CardPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_type', models.CharField(max_length=20)),
                ('last_four', models.CharField(max_length=4)),
                ('expiry_month', models.CharField(max_length=2)),
                ('expiry_year', models.CharField(max_length=4)),
                ('card_holder_name', models.CharField(max_length=255)),
                ('card_nickname', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='useraddress',
            index=models.Index(fields=['user', 'is_default'], name='authenticat_user_id_3eae38_idx'),
        ),
        migrations.AddIndex(
            model_name='useraddress',
            index=models.Index(fields=['user', 'address_type'], name='authenticat_user_id_22aa59_idx'),
        ),
        migrations.AddIndex(
            model_name='useraddress',
            index=models.Index(fields=['pin_code'], name='authenticat_pin_cod_3e8470_idx'),
        ),
        migrations.AddIndex(
            model_name='useraddress',
            index=models.Index(fields=['city', 'state'], name='authenticat_city_43a8d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='useraddress',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='unique_default_address_per_user'),
        ),
        migrations.AddIndex(
            model_name='upipaymentmethod',
            index=models.Index(fields=['user', 'upi_id'], name='authenticat_user_id_6d82dd_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistorygroup',
            index=models.Index(fields=['user'], name='authenticat_user_id_94c6e6_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistorygroup',
            index=models.Index(fields=['updated_at'], name='authenticat_updated_f4fcb7_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['search_group'], name='authenticat_search__e0cc1e_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['query'], name='authenticat_query_484fe4_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['searched_at'], name='authenticat_searche_7732aa_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['category'], name='authenticat_categor_4b3215_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payment', 'action'], name='authenticat_payment_879629_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['created_at'], name='authenticat_created_6f6438_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['user', 'status'], name='authenticat_user_id_2fada0_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['transaction_id'], name='authenticat_transac_b48a5c_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['created_at'], name='authenticat_created_fa2779_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['billing_address'], name='authenticat_billing_0cc500_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['gateway_name'], name='authenticat_gateway_90ec72_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['payment_type'], name='authenticat_payment_67d490_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='authenticat_order_i_95a697_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product_id'], name='authenticat_product_adf242_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['status'], name='authenticat_status_572eac_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product_sku'], name='authenticat_product_a55840_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user'], name='authenticat_user_id_b2eba3_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_date'], name='authenticat_order_d_96c889_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='authenticat_status_e6d35c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shipping_address'], name='authenticat_shippin_7ccb12_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='authenticat_order_n_223207_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tracking_number'], name='authenticat_trackin_3ae5c0_idx'),
        ),
        migrations.AddIndex(
            model_name='expiringtoken',
            index=models.Index(fields=['expiry'], name='authenticat_expiry_67b8b6_idx'),
        ),
        migrations.AddIndex(
            model_name='expiringtoken',
            index=models.Index(fields=['last_used'], name='authenticat_last_us_76e65e_idx'),
        ),
        migrations.AddIndex(
            model_name='expiringtoken',
            index=models.Index(fields=['device_type'], name='authenticat_device__1dfbc3_idx'),
        ),
        migrations.AddIndex(
            model_name='customersupportticket',
            index=models.Index(fields=['user'], name='authenticat_user_id_19722e_idx'),
        ),
        migrations.AddIndex(
            model_name='customersupportticket',
            index=models.Index(fields=['status'], name='authenticat_status_0ee21a_idx'),
        ),
        migrations.AddIndex(
            model_name='customersupportticket',
            index=models.Index(fields=['created_at'], name='authenticat_created_11bd45_idx'),
        ),
        migrations.AddIndex(
            model_name='customerchat',
            index=models.Index(fields=['ticket'], name='authenticat_ticket__2b5da0_idx'),
        ),
        migrations.AddIndex(
            model_name='customerchat',
            index=models.Index(fields=['timestamp'], name='authenticat_timesta_a149b1_idx'),
        ),
        migrations.AddIndex(
            model_name='customerchat',
            index=models.Index(fields=['is_user_message'], name='authenticat_is_user_1667ec_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart'], name='authenticat_cart_id_d36055_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['product_id'], name='authenticat_product_01c935_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['added_at'], name='authenticat_added_a_4ad52b_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['is_available'], name='authenticat_is_avai_48307b_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['is_saved_for_later'], name='authenticat_is_save_dea54b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product_id', 'product_variant')},
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user'], name='authenticat_user_id_88b9bc_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['updated_at'], name='authenticat_updated_753b5e_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['session_id'], name='authenticat_session_c83c37_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['expires_at'], name='authenticat_expires_036714_idx'),
        ),
        migrations.AddIndex(
            model_name='cardpaymentmethod',
            index=models.Index(fields=['user', 'card_type'], name='authenticat_user_id_d0c183_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='authenticat_usernam_61ef80_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='authenticat_email_d74434_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='authenticat_phone_n_87acce_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_verified'], name='authenticat_is_veri_984052_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['verification_token'], name='authenticat_verific_4a1936_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['reset_password_token'], name='authenticat_reset_p_4d9ce3_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_of_birth'], name='authenticat_date_of_858755_idx'),
        ),
    ]
