# Generated by Django 4.2.10 on 2025-06-28 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customersupportticket_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='JWTSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(help_text='JWT ID from token', max_length=100, unique=True)),
                ('device_type', models.CharField(choices=[('ANDROID', 'Android App'), ('WEB', 'Web Browser'), ('IOS', 'iOS App'), ('API', 'API Client')], default='API', max_length=20)),
                ('device_id', models.CharField(blank=True, help_text='Unique device identifier', max_length=255, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address when session was created', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(help_text='When the JWT token expires')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jwt_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='authenticat_user_id_e2a3b0_idx'), models.Index(fields=['jti'], name='authenticat_jti_fdd2a8_idx'), models.Index(fields=['expires_at'], name='authenticat_expires_571481_idx'), models.Index(fields=['device_type'], name='authenticat_device__1fed8d_idx'), models.Index(fields=['device_id'], name='authenticat_device__5ee213_idx')],
            },
        ),
    ]
