# Generated by Django 4.2.10 on 2025-06-29 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_jwtsession'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cart',
            name='authenticat_user_id_88b9bc_idx',
        ),
        migrations.AddField(
            model_name='cart',
            name='store_id',
            field=models.CharField(default=1, help_text='Store identifier', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='store_name',
            field=models.CharField(blank=True, help_text='Store name for display', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'store_id'], name='authenticat_user_id_3653a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('user', 'store_id'), name='unique_user_store_cart'),
        ),
    ]
