# Generated by Django 4.2.10 on 2025-07-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_add_multi_store_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_password_otp',
            field=models.CharField(blank=True, help_text='6-digit OTP for password reset', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_password_otp_expires',
            field=models.DateTimeField(blank=True, help_text='Password reset OTP expiry time', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_otp',
            field=models.CharField(blank=True, help_text='6-digit OTP for verification', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_otp_expires',
            field=models.DateTimeField(blank=True, help_text='OTP expiry time', null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['verification_otp'], name='authenticat_verific_85d648_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['reset_password_otp'], name='authenticat_reset_p_813851_idx'),
        ),
    ]
