# Generated by Django 4.2.10 on 2025-07-25 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_add_otp_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='legacy_shipping_address',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='legacy_billing_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
