# Generated by Django 4.2.10 on 2025-07-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_legacy_address_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email address already exists.'}, help_text='Required. Enter a valid email address.', max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
