# Generated by Django 4.2.10 on 2025-08-12 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.CharField(blank=True, default='+91', help_text='Country code with + prefix (e.g., +91, +1)', max_length=5, null=True, validators=[django.core.validators.RegexValidator(message='Country code must start with + and be 1-4 digits (e.g., +91, +1).', regex='^\\+\\d{1,4}$')]),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='country_code',
            field=models.CharField(blank=True, default='+91', help_text='Country code with + prefix (e.g., +91, +1)', max_length=5, null=True, validators=[django.core.validators.RegexValidator(message='Country code must start with + and be 1-4 digits (e.g., +91, +1).', regex='^\\+\\d{1,4}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='10-digit phone number without country code', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='phone_number',
            field=models.CharField(blank=True, help_text='10-digit phone number without country code', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['country_code', 'phone_number'], name='authenticat_country_9d3115_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_number__isnull', False), models.Q(('phone_number', ''), _negated=True)), fields=('country_code', 'phone_number'), name='unique_country_phone_number'),
        ),
    ]
