# Generated by Django 4.2.10 on 2025-08-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_country_code_useraddress_country_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Payment amount - secured with default value for data integrity', max_digits=12),
        ),
    ]
