"""
Django settings for Customer_API project.
Generated by 'django-admin startproject' using Django.
"""
# Import logging at the top
import logging
import logging.config
from pathlib import Path
from datetime import timedelta
import os
import dj_database_url
from django.core.management.utils import get_random_secret_key

# Load environment variables
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', get_random_secret_key())

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Site URL Configuration for Payment Gateways
SITE_PROTOCOL = os.environ.get('SITE_PROTOCOL', 'https')
SITE_DOMAIN = os.environ.get('SITE_DOMAIN', 'localhost')

# Set the proper URL configuration to include port in API URLs
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Logging Configuration
LOG_DIR = os.path.join(BASE_DIR, 'logs')
LOG_LEVEL = os.environ.get('LOG_LEVEL', 'INFO').upper()
LOG_FILE_PATH = os.environ.get('LOG_FILE_PATH', 'error.log')

# Create logs directory
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)

# Define LOGGING before it's used
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'file': {
            'level': LOG_LEVEL,
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_DIR, 'django.log'),
            'formatter': 'verbose',
        },
        'console': {
            'level': LOG_LEVEL,
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        }
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': LOG_LEVEL,
            'propagate': True,
        },
        'django.request': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': False,
        },
    }
}

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',  # For token blacklisting
    'corsheaders',
    'authentication',
    'whitenoise.runserver_nostatic',  # Static files serving
    'defender',  # For brute force protection
    'storages',  # For cloud storage
]

# Add development-specific apps
if DEBUG:
    INSTALLED_APPS += [
        'django_extensions',  # Useful development tools
        'debug_toolbar',      # Django Debug Toolbar
        'drf_yasg',          # Swagger API documentation
    ]
    
    # Swagger settings for API documentation
    SWAGGER_SETTINGS = {
        'SECURITY_DEFINITIONS': {
            'Token': {
                'type': 'apiKey',
                'name': 'Authorization',
                'in': 'header'
            },
            'JWT': {
                'type': 'apiKey',
                'name': 'Authorization',
                'in': 'header'
            }
        },
        'USE_SESSION_AUTH': False,
        'JSON_EDITOR': True,
    }

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'authentication.security_middleware.IPThrottlingMiddleware',  # Advanced IP protection (Custom Middleware)
    'authentication.security_middleware.SecurityAuditMiddleware',  # Security monitoring (Custom Middleware)
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add WhiteNoise for serving static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'authentication.security_middleware.SessionSecurityMiddleware',  # Session security (Custom Middleware)
    'defender.middleware.FailedLoginMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'authentication.middleware.AndroidSecurityHeadersMiddleware', # Headers for Android (Custom Middleware)
    'Customer_API.middleware.MobileOptimizedGZipMiddleware', # GZip optimization (Custom Middleware)
    'Customer_API.middleware.MobileAPIVersionMiddleware', # API versioning (Custom Middleware)
    'authentication.middleware.AndroidCacheMiddleware', # caching (Android) (Custom Middleware)
]

# Add Debug Toolbar middleware in development
if DEBUG:
    gzip_index = MIDDLEWARE.index('Customer_API.middleware.MobileOptimizedGZipMiddleware')
    MIDDLEWARE.insert(gzip_index + 1, 'debug_toolbar.middleware.DebugToolbarMiddleware')
    INTERNAL_IPS = ['127.0.0.1']  # Required for Debug Toolbar

ROOT_URLCONF = 'Customer_API.urls'

TOKEN_EXPIRY_TIME = int(os.environ.get('TOKEN_EXPIRY_TIME', '1'))  # 1 days default for mobile
TOKEN_EXPIRY_TIME_LOGIN = int(os.environ.get('TOKEN_EXPIRY_TIME_LOGIN', '7'))  # 7 days default for login tokens
OTP_EXPIRY_TIME = int(os.environ.get('OTP_EXPIRY_TIME', '25'))  # 25 minutes default for OTPs

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Customer_API.wsgi.application'

# Cache configuration
ANDROID_CACHE_TIMEOUT = int(os.environ.get('CACHE_TIMEOUT', '300'))  # Default 5 minutes, can be overridden
CACHE_BACKEND = os.environ.get('CACHE_BACKEND', 'django.core.cache.backends.locmem.LocMemCache')
CACHE_LOCATION = os.environ.get('CACHE_LOCATION', 'android-api-cache')

if DEBUG:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': CACHE_LOCATION,
            'TIMEOUT': ANDROID_CACHE_TIMEOUT,
            'OPTIONS': {
                'MAX_ENTRIES': int(os.environ.get('CACHE_MAX_ENTRIES', '1000'))
            }
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': CACHE_BACKEND,
            'LOCATION': os.path.join(BASE_DIR, 'cache'),
            'TIMEOUT': ANDROID_CACHE_TIMEOUT,
            'OPTIONS': {
                'MAX_ENTRIES': int(os.environ.get('CACHE_MAX_ENTRIES', '1000'))
            }
        }
    }

# Database Configuration
# Using standard PostgreSQL connection parameters
if os.environ.get('DATABASE_URL'):
    # If a database URL is provided, use it (useful for platforms like Heroku)
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Otherwise use the standard database settings from environment variables
    DATABASES = {
        'default': {
            'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.postgresql'),
            'NAME': os.environ.get('DB_NAME', 'S2Cart_db'),
            'USER': os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
            'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '600')),
            'OPTIONS': {
                'connect_timeout': int(os.environ.get('DB_CONNECT_TIMEOUT', '10')),
            }
        }
    }

# Fall back to SQLite if PostgreSQL configuration is incomplete
if (DATABASES['default']['ENGINE'] == 'django.db.backends.postgresql' and 
    (not DATABASES['default'].get('NAME') or 
     not DATABASES['default'].get('USER') or 
     not DATABASES['default'].get('PASSWORD'))
   ):
    print("WARNING: Incomplete PostgreSQL configuration, falling back to SQLite")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        'OPTIONS': {'max_similarity': float(os.environ.get('PASSWORD_MAX_SIMILARITY', '0.7'))}  # Configurable similarity check
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': int(os.environ.get('PASSWORD_MIN_LENGTH', '8'))},  # Configurable minimum length
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Enhanced security settings for military-grade protection
MAX_FAILED_LOGIN_ATTEMPTS = int(os.environ.get('MAX_FAILED_LOGIN_ATTEMPTS', '3'))
ACCOUNT_LOCKOUT_MINUTES = int(os.environ.get('ACCOUNT_LOCKOUT_MINUTES', '60'))
BRUTEFORCE_PROTECTION_ENABLED = os.environ.get('BRUTEFORCE_PROTECTION_ENABLED', 'True').lower() == 'true'
IP_BASED_LOCKOUT_THRESHOLD = int(os.environ.get('IP_BASED_LOCKOUT_THRESHOLD', '10'))
IP_LOCKOUT_DURATION = int(os.environ.get('IP_LOCKOUT_DURATION', '300'))
SESSION_EXPIRE_AT_BROWSER_CLOSE = os.environ.get('SESSION_EXPIRE_AT_BROWSER_CLOSE', 'True').lower() == 'true'
SESSION_COOKIE_AGE = int(os.environ.get('SESSION_COOKIE_AGE', '3600'))  # 1 hour default

# Custom user model
AUTH_USER_MODEL = 'authentication.User'

# Internationalization
LANGUAGE_CODE = os.environ.get('LANGUAGE_CODE', 'en-us')
TIME_ZONE = os.environ.get('TIME_ZONE', 'Asia/Kolkata')  # Default to Indian time zone
USE_I18N = os.environ.get('USE_I18N', 'True').lower() == 'true'
USE_TZ = os.environ.get('USE_TZ', 'True').lower() == 'true'

# Static files (CSS, JavaScript, Images)
STATIC_URL = os.environ.get('STATIC_URL', '/static/')
STATIC_ROOT = os.path.join(BASE_DIR, os.environ.get('STATIC_ROOT_PATH', 'staticfiles'))
STATICFILES_STORAGE = os.environ.get('STATICFILES_STORAGE', 'whitenoise.storage.CompressedManifestStaticFilesStorage')

# Media files
MEDIA_URL = os.environ.get('MEDIA_URL', '/media/')
MEDIA_ROOT = os.path.join(BASE_DIR, os.environ.get('MEDIA_ROOT_PATH', 'media'))

# Google Cloud Storage Settings
if os.environ.get('USE_GCS', 'False').lower() == 'true':
    try:
        import google.cloud.storage
        GS_BUCKET_NAME = os.environ.get('GCS_BUCKET_NAME')
        DEFAULT_FILE_STORAGE = os.environ.get('GCS_DEFAULT_FILE_STORAGE', 'storages.backends.gcloud.GoogleCloudStorage')
        STATICFILES_STORAGE = os.environ.get('GCS_STATICFILES_STORAGE', 'storages.backends.gcloud.GoogleCloudStorage')
        GS_DEFAULT_ACL = os.environ.get('GCS_DEFAULT_ACL', 'publicRead')
        GS_QUERYSTRING_AUTH = os.environ.get('GCS_QUERYSTRING_AUTH', 'False').lower() == 'true'
        # Optional: if you want to serve media from a subdirectory in the bucket
        GS_MEDIA_LOCATION = os.environ.get('GCS_MEDIA_LOCATION', 'media')
        GS_STATIC_LOCATION = os.environ.get('GCS_STATIC_LOCATION', 'static')
    except ImportError:
        import logging
        logging.warning("Google Cloud Storage requested but libraries not available. Using local storage.")

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings optimized for Android with JWT
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'authentication.models.ExpiringTokenAuthentication',  # Keep for backward compatibility
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.environ.get('REST_FRAMEWORK_ANON_THROTTLE_RATE', '50/minute'),  # Reduced from 100
        'user': os.environ.get('REST_FRAMEWORK_USER_THROTTLE_RATE', '200/minute'),  # Reduced from 300
        'login': os.environ.get('REST_FRAMEWORK_LOGIN_THROTTLE_RATE', '3/minute'),  # Reduced from 5
        'payment': os.environ.get('REST_FRAMEWORK_PAYMENT_THROTTLE_RATE', '10/hour'),  # Payment operations
        'registration': os.environ.get('REST_FRAMEWORK_REGISTRATION_THROTTLE_RATE', '5/hour'),  # Registration
    },
    'EXCEPTION_HANDLER': 'Customer_API.exceptions.custom_exception_handler',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': int(os.environ.get('REST_FRAMEWORK_PAGE_SIZE', '20')),  # Reduced for mobile optimization
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.AcceptHeaderVersioning',
    'DEFAULT_VERSION': os.environ.get('REST_FRAMEWORK_DEFAULT_VERSION', '1.0'),
    'ALLOWED_VERSIONS': os.environ.get('REST_FRAMEWORK_ALLOWED_VERSIONS', '1.0').split(','),
    'DEFAULT_CACHE_RESPONSE_TIMEOUT': int(os.environ.get('REST_FRAMEWORK_CACHE_TIMEOUT', '300')),  # 5 minutes cache for mobile
}

# JWT Settings for djangorestframework-simplejwt
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=int(os.environ.get('JWT_ACCESS_TOKEN_DAYS', '7'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.environ.get('JWT_REFRESH_TOKEN_DAYS', '30'))),
    'ROTATE_REFRESH_TOKENS': os.environ.get('JWT_ROTATE_REFRESH_TOKENS', 'True').lower() == 'true',
    'BLACKLIST_AFTER_ROTATION': os.environ.get('JWT_BLACKLIST_AFTER_ROTATION', 'True').lower() == 'true',
    'UPDATE_LAST_LOGIN': os.environ.get('JWT_UPDATE_LAST_LOGIN', 'True').lower() == 'true',
    
    'ALGORITHM': os.environ.get('JWT_ALGORITHM', 'HS256'),
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': os.environ.get('JWT_ISSUER', 'Customer-API'),
    'JSON_ENCODER': None,
    'JWK_URL': None,
    'LEEWAY': int(os.environ.get('JWT_LEEWAY', '0')),
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    
    'JTI_CLAIM': 'jti',
    
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=int(os.environ.get('JWT_SLIDING_TOKEN_MINUTES', '5'))),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=int(os.environ.get('JWT_SLIDING_REFRESH_DAYS', '1'))),
    
    # Token blacklist settings
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    
    # Custom claims
    'TOKEN_OBTAIN_SERIALIZER': 'authentication.serializers.CustomTokenObtainPairSerializer',
}

# CORS settings optimized for Android
CORS_ALLOW_ALL_ORIGINS = False  # More secure
CORS_ALLOWED_ORIGINS = [
    "file://",  # Required for Android WebView
    "https://securegw.paytm.in",
    "https://securegw-stage.paytm.in",
    *os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS'
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-token-auth',  # Custom header for token auth
    'cache-control'
]
CORS_EXPOSE_HEADERS = [
    'content-length',
    'content-type',
    'content-disposition'
]

# CSRF settings
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'True').lower() == 'true'
CSRF_TRUSTED_ORIGINS = [
    "https://securegw.paytm.in",
    "https://securegw-stage.paytm.in",
    *os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
]
CSRF_COOKIE_HTTPONLY = os.environ.get('CSRF_COOKIE_HTTPONLY', 'False').lower() == 'true'
CSRF_USE_SESSIONS = os.environ.get('CSRF_USE_SESSIONS', 'False').lower() == 'true'
CSRF_COOKIE_SAMESITE = os.environ.get('CSRF_COOKIE_SAMESITE', None)

# Session settings
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = int(os.environ.get('SESSION_COOKIE_AGE', '86400'))  # From env or 24 hours default
SESSION_EXPIRE_AT_BROWSER_CLOSE = os.environ.get('SESSION_EXPIRE_AT_BROWSER_CLOSE', 'True').lower() == 'true'
SESSION_COOKIE_NAME = 'sessionid'
SESSION_COOKIE_PATH = '/'
SESSION_COOKIE_SAMESITE = os.environ.get('SESSION_COOKIE_SAMESITE', 'Lax')
SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'False').lower() == 'true'

# Security settings - applied to both development and production
SECURE_CONTENT_TYPE_NOSNIFF = os.environ.get('SECURE_CONTENT_TYPE_NOSNIFF', 'True').lower() == 'true'
X_FRAME_OPTIONS = os.environ.get('X_FRAME_OPTIONS', 'DENY')

# Production security settings
if not DEBUG:
    # Security settings
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'True').lower() == 'true'
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000'))  # 1 year default
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True').lower() == 'true'
    SECURE_HSTS_PRELOAD = os.environ.get('SECURE_HSTS_PRELOAD', 'True').lower() == 'true'
    SECURE_CONTENT_TYPE_NOSNIFF = True  # Always true in production
    SECURE_BROWSER_XSS_FILTER = os.environ.get('SECURE_BROWSER_XSS_FILTER', 'True').lower() == 'true'
    
    # Content Security Policy
    CSP_DEFAULT_SRC = os.environ.get('CSP_DEFAULT_SRC', "'self'").split(',')
    CSP_SCRIPT_SRC = os.environ.get('CSP_SCRIPT_SRC', "'self',https://securegw.paytm.in,https://securegw-stage.paytm.in").split(',')
    CSP_CONNECT_SRC = os.environ.get('CSP_CONNECT_SRC', "'self',https://securegw.paytm.in,https://securegw-stage.paytm.in").split(',')
    CSP_FRAME_SRC = os.environ.get('CSP_FRAME_SRC', "'self',https://securegw.paytm.in,https://securegw-stage.paytm.in").split(',')
else:
    # Development-only settings
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_SECONDS = 0

# Email settings
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend'
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@S2Cart.com')

# Defender settings (brute force protection)
DEFENDER_REDIS_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
DEFENDER_LOGIN_FAILURE_LIMIT = int(os.environ.get('DEFENDER_LOGIN_FAILURE_LIMIT', '5'))
DEFENDER_COOLOFF_TIME = int(os.environ.get('DEFENDER_COOLOFF_TIME', '300'))  # 5 minutes
DEFENDER_LOCKOUT_TEMPLATE = None  # Use API response instead
DEFENDER_LOCK_OUT_BY_IP_AND_USERNAME = os.environ.get('DEFENDER_LOCK_OUT_BY_IP_AND_USERNAME', 'True').lower() == 'true'

# Sentry configuration for error tracking (if available)
SENTRY_DSN = os.environ.get('SENTRY_DSN', '')
if SENTRY_DSN and not DEBUG:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration
        
        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[DjangoIntegration()],
            traces_sample_rate=float(os.environ.get('SENTRY_TRACES_SAMPLE_RATE', '0.1')),
            send_default_pii=os.environ.get('SENTRY_SEND_DEFAULT_PII', 'True').lower() == 'true',
            # Send email for fatal errors
            before_send=lambda event, hint: event
        )
    except ImportError:
        import logging
        logging.warning("Sentry configuration requested but sentry_sdk not available.")

# Error email settings for production
if not DEBUG:
    # Email critical errors to admins in production
    ADMINS = [('Tech Admin', os.environ.get('ADMIN_EMAIL', 's2cartofficial'))]
    SERVER_EMAIL = os.environ.get('SERVER_EMAIL', 's2cartofficial')
    EMAIL_SUBJECT_PREFIX = os.environ.get('EMAIL_SUBJECT_PREFIX', '[S2Cart API Error] ')
    
    # Configure error reporting through email
    LOGGING['handlers']['mail_admins'] = {
        'level': 'ERROR',
        'class': 'django.utils.log.AdminEmailHandler',
        'filters': ['require_debug_false'],
        'include_html': True,
    }
    
    # Make sure critical errors are emailed
    LOGGING['loggers']['django.request']['handlers'] = ['mail_admins', 'file']
    LOGGING['loggers']['django.security'] = {
        'handlers': ['mail_admins', 'file'],
        'level': 'ERROR',
        'propagate': False,
    }

# Additional security settings for production
ANDROID_API_MINIMUM_VERSION = os.environ.get('ANDROID_API_MINIMUM_VERSION', '1.0.0')
ANDROID_API_LATEST_VERSION = os.environ.get('ANDROID_API_LATEST_VERSION', '1.0.0')
ANDROID_FORCE_UPDATE_VERSIONS = os.environ.get('ANDROID_FORCE_UPDATE_VERSIONS', '').split(',')
ANDROID_MAINTENANCE_MODE = os.environ.get('ANDROID_MAINTENANCE_MODE', 'False').lower() == 'true'

# API Rate limiting
API_RATE_LIMIT_ENABLED = os.environ.get('API_RATE_LIMIT_ENABLED', 'True').lower() == 'true'

# Paytm Configuration
PAYTM_MERCHANT_ID = os.environ.get('PAYTM_MERCHANT_ID', '')
PAYTM_MERCHANT_KEY = os.environ.get('PAYTM_MERCHANT_KEY', '')
PAYTM_WEBSITE = os.environ.get('PAYTM_WEBSITE', 'WEBSTAGING')
PAYTM_INDUSTRY_TYPE_ID = os.environ.get('PAYTM_INDUSTRY_TYPE_ID', 'Retail')
PAYTM_CHANNEL_ID = os.environ.get('PAYTM_CHANNEL_ID', 'WEB')
PAYTM_TEST_MODE = os.environ.get('PAYTM_TEST_MODE', 'True').lower() == 'true'
PAYTM_TOKEN_URL = os.environ.get('PAYTM_TOKEN_URL', 'https://securegw-stage.paytm.in/theia/api/v1/initiateTransaction')
PAYTM_STATUS_URL = os.environ.get('PAYTM_STATUS_URL', 'https://securegw-stage.paytm.in/merchant-status/getTxnStatus')

# PhonePe Configuration
PHONEPE_TEST_MODE = os.environ.get('PHONEPE_TEST_MODE', 'False').lower() == 'true'
PHONEPE_MERCHANT_ID = os.environ.get('PHONEPE_MERCHANT_ID', '')
PHONEPE_SALT_KEY = os.environ.get('PHONEPE_SALT_KEY', '')
PHONEPE_CALLBACK_URL_PREFIX = os.environ.get('PHONEPE_CALLBACK_URL_PREFIX', '/api/auth/payments/phonepe/callback/')
PHONEPE_CLIENT_ID = os.environ.get('PHONEPE_CLIENT_ID', '')
PHONEPE_CLIENT_SECRET = os.environ.get('PHONEPE_CLIENT_SECRET', '')
PHONEPE_CLIENT_VERSION = os.environ.get('PHONEPE_CLIENT_VERSION', '1.0.0')
PHONEPE_PRODUCTION_URL = os.environ.get('PHONEPE_PRODUCTION_URL', 'https://api.phonepe.com/apis/hermes')
PHONEPE_STAGING_URL = os.environ.get('PHONEPE_STAGING_URL', 'https://api-preprod.phonepe.com/apis/hermes')
PHONEPE_REDIRECT_URL = os.environ.get('PHONEPE_REDIRECT_URL', 'https://customer-api.s2cart.me/api/auth/payments/phonepe/redirect/')

# Site URL for callback URLs
SITE_URL = os.environ.get('SITE_URL', 'https://customer-api.s2cart.me')

# API Version
API_VERSION = os.environ.get('API_VERSION', '1.0.0')

# Cart Configuration
MAX_CARTS_PER_USER = int(os.environ.get('MAX_CARTS_PER_USER', '5'))  # Maximum carts per user (different stores)

# ========== Email Security & Validation Settings ==========
# Enable/disable enhanced email validation system
EMAIL_SECURITY_ENABLED = os.environ.get('EMAIL_SECURITY_ENABLED', 'True').lower() == 'true'

# Email submission rate limiting settings
EMAIL_RATE_LIMIT_REGISTRATION_ATTEMPTS = int(os.environ.get('EMAIL_RATE_LIMIT_REGISTRATION_ATTEMPTS', '3'))
EMAIL_RATE_LIMIT_REGISTRATION_WINDOW = int(os.environ.get('EMAIL_RATE_LIMIT_REGISTRATION_WINDOW', '15'))
EMAIL_RATE_LIMIT_LOGIN_ATTEMPTS = int(os.environ.get('EMAIL_RATE_LIMIT_LOGIN_ATTEMPTS', '5'))
EMAIL_RATE_LIMIT_LOGIN_WINDOW = int(os.environ.get('EMAIL_RATE_LIMIT_LOGIN_WINDOW', '10'))
EMAIL_RATE_LIMIT_PASSWORD_RESET_ATTEMPTS = int(os.environ.get('EMAIL_RATE_LIMIT_PASSWORD_RESET_ATTEMPTS', '3'))
EMAIL_RATE_LIMIT_PASSWORD_RESET_WINDOW = int(os.environ.get('EMAIL_RATE_LIMIT_PASSWORD_RESET_WINDOW', '30'))

# Email validation feature toggles
EMAIL_VALIDATION_ENABLE_MX_CHECK = os.environ.get('EMAIL_VALIDATION_ENABLE_MX_CHECK', 'False').lower() == 'true'
EMAIL_VALIDATION_BLOCK_TEMP_EMAILS = os.environ.get('EMAIL_VALIDATION_BLOCK_TEMP_EMAILS', 'True').lower() == 'true'
EMAIL_VALIDATION_BLOCK_RESERVED_USERNAMES = os.environ.get('EMAIL_VALIDATION_BLOCK_RESERVED_USERNAMES', 'True').lower() == 'true'
EMAIL_VALIDATION_ENABLE_SUSPICIOUS_PATTERN_CHECK = os.environ.get('EMAIL_VALIDATION_ENABLE_SUSPICIOUS_PATTERN_CHECK', 'True').lower() == 'true'

# Custom domain and username restrictions
EMAIL_VALIDATION_CUSTOM_BLOCKED_DOMAINS = [
    domain.strip() for domain in os.environ.get('EMAIL_VALIDATION_CUSTOM_BLOCKED_DOMAINS', '').split(',') 
    if domain.strip()
]
EMAIL_VALIDATION_CUSTOM_RESERVED_USERNAMES = [
    username.strip().lower() for username in os.environ.get('EMAIL_VALIDATION_CUSTOM_RESERVED_USERNAMES', '').split(',') 
    if username.strip()
]

# Email validation strictness level
EMAIL_VALIDATION_STRICTNESS = os.environ.get('EMAIL_VALIDATION_STRICTNESS', 'strict').lower()

# DNS validation timeout
EMAIL_VALIDATION_DNS_TIMEOUT = int(os.environ.get('EMAIL_VALIDATION_DNS_TIMEOUT', '5'))
