# Generated by Django 4.2.10 on 2025-12-27 11:46

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=255)),
                ('slug', models.SlugField(help_text='SEO-friendly URL slug', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description', null=True)),
                ('image', models.ImageField(blank=True, help_text='Category image', null=True, upload_to='categories/')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for display')),
                ('is_active', models.BooleanField(default=True, help_text='Whether category is visible to customers')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured category for homepage')),
                ('meta_title', models.CharField(blank=True, help_text='SEO meta title', max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category for hierarchy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name', max_length=255)),
                ('slug', models.SlugField(help_text='SEO-friendly URL slug', max_length=255, unique=True)),
                ('sku', models.CharField(help_text='Stock Keeping Unit', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Product description', null=True)),
                ('short_description', models.CharField(blank=True, help_text='Short description for listings', max_length=500, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Regular price in INR', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price (if applicable)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage for display', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Available stock quantity')),
                ('low_stock_threshold', models.PositiveIntegerField(default=10, help_text='Low stock alert threshold')),
                ('is_track_stock', models.BooleanField(default=True, help_text='Whether to track inventory')),
                ('allow_backorder', models.BooleanField(default=False, help_text='Allow orders when out of stock')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, help_text='Weight in kg', max_digits=10, null=True)),
                ('dimensions', models.JSONField(blank=True, help_text='Product dimensions (length, width, height in cm)', null=True)),
                ('brand', models.CharField(blank=True, help_text='Product brand', max_length=100, null=True)),
                ('attributes', models.JSONField(blank=True, help_text='Product attributes (color, size, material, etc.)', null=True)),
                ('variants', models.JSONField(blank=True, help_text='Product variants with pricing', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether product is visible to customers')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured product for promotions')),
                ('is_new', models.BooleanField(default=True, help_text='Mark as new arrival')),
                ('is_bestseller', models.BooleanField(default=False, help_text='Mark as bestseller')),
                ('meta_title', models.CharField(blank=True, help_text='SEO meta title', max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description', null=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO keywords', max_length=500, null=True)),
                ('tax_class', models.CharField(choices=[('STANDARD', 'Standard GST'), ('REDUCED', 'Reduced GST'), ('ZERO', 'Zero GST'), ('EXEMPT', 'GST Exempt')], default='STANDARD', help_text='Tax classification', max_length=50)),
                ('is_digital', models.BooleanField(default=False, help_text='Digital product (no shipping)')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of product views')),
                ('sold_count', models.PositiveIntegerField(default=0, help_text='Number of units sold')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='When product was published', null=True)),
                ('category', models.ForeignKey(blank=True, help_text='Product category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='Product in wishlist', on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='products.product')),
                ('user', models.ForeignKey(help_text='User who owns the wishlist', on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'product'], name='products_wi_user_id_7792c0_idx')],
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, help_text='Review title', max_length=255, null=True)),
                ('comment', models.TextField(blank=True, help_text='Review comment', null=True)),
                ('is_verified_purchase', models.BooleanField(default=False, help_text='Whether user purchased the product')),
                ('is_approved', models.BooleanField(default=True, help_text='Whether review is approved for display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='Product being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
                ('user', models.ForeignKey(help_text='User who wrote the review', on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'is_approved'], name='products_pr_product_160d92_idx'), models.Index(fields=['rating'], name='products_pr_rating_0e31b2_idx'), models.Index(fields=['created_at'], name='products_pr_created_da486c_idx')],
                'unique_together': {('product', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Product image file', upload_to='products/')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=255, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary image for product listing')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='Product this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ['-is_primary', 'display_order'],
                'indexes': [models.Index(fields=['product', 'is_primary'], name='products_pr_product_1b7905_idx'), models.Index(fields=['display_order'], name='products_pr_display_5b8ce6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='products_pr_is_acti_ca4d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured'], name='products_pr_is_feat_a5d7cd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_pr_categor_9edb3d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='products_pr_price_9b1a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock_quantity'], name='products_pr_stock_q_ba97b5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='products_pr_created_52f0d7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sold_count'], name='products_pr_sold_co_4f0e44_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='products_ca_slug_da4386_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='products_ca_is_acti_a2d000_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='products_ca_parent__f3c24e_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['display_order'], name='products_ca_display_a74932_idx'),
        ),
    ]
